### PR TITLE
Adapted commonwealth british-english pops from arandomperson5000 and nwomod

### PR DESCRIPTION
**Pull request by Outta-my-way-burrocrat**
Pops are divided between home island british and multicultural commonwealth english
https://github.com/simsulla/nwomod

### CODE REVIEW

**Comment by settintotrieste** [comment]
I prefer overseas british pops to be british rather than english since that would capture the scots, welsh and irishmen who also migrated abroad.

**Comment by Outta-my-way-burrocrat** [comment]
@settintotrieste Ok. Overall, have my past contributions improved the mod? I never got to see any of the discussions on Discord.

**Comment by ccfox** [comment]
Yes, though if you are able - could you join the discord?

**Comment by settintotrieste** [comment]
@Outta-my-way-burrocrat Yes, your contributions have improved the mod a lot, especially in the area of bugfixing. Without your input there, a number of critical bugs would never have been found and fixed.

**Comment by Outta-my-way-burrocrat** [comment]
Thank you both, that means a lot.

**Pull request closed without merging**
