### PR TITLE
More dynamic ahistorical outcomes

### PR DESCRIPTION
**Pull request by ARR8**
Newfoundland, Six-day war, Trst/Trieste

Vary world events slightly, expanded AI logic

### CODE REVIEW

**Comment by settintotrieste** [comment]
This is great! However there is one thing to note when it comes to ai_chance factor and that is all factor values must be less or equal to 1 if you wish to randomise AI choice. An example would be option 1: factor 10 and option 2: factor 90. The AI will still always choose option 1 as it takes factor 10 as 100% and the AI scrolls down the choices and select the first 100% ai_chance.

**Comment by ARR8** [comment]
Uhh...give me a second.

**Comment by ARR8** [comment]
Fixed, plus a few more. That's really good to know now, and not after I started doing more of those.

**Comment by settintotrieste** [comment]
Yes it thought so too myself in the beginning but apparently it's not the case. There's a lot of inconsistency in the Victoria game's programming which I believe is attributed to different programmers who did the various parts of the code. It's quite telling when some commands are written using British spelling and others in American spelling.

**Pull request merged**
