### PR TITLE
Update CAT - Catalonia.txt

### PR DESCRIPTION
**Pull request by ccfox**
Edited accepted cultures to match Spain.

### CODE REVIEW

**Comment by Outta-my-way-burrocrat** [comment]
Are you going to remove the white_spanish culture from other places as well? It only appears in Spain 1992,

**Comment by ccfox** [comment]
@Outta-my-way-burrocrat Is it in other places that it shouldn't be? Its probably in Spain for 1992 to represent immigrants from South and Central America.

**Comment by Outta-my-way-burrocrat** [comment]
xac_form_union and xna_form_union still make white_spanish an accepted culture and the pink_tide decision checks if the country is primary white_spanish. Several superstates still have white_spanish as primary or accepted culture in their history files.

**Comment by ccfox** [comment]
I'll take a look at them.

**Comment by Outta-my-way-burrocrat** [comment]
Thank you.

**Pull request merged**
