### PR TITLE
Update buildings.txt

### PR DESCRIPTION
**Pull request by TK3600**
1. Increased the material build cost of factory by 10x. This will balance the lack of need for raw material.
2. Increased build time of factory by 2x to slow down unreasonably fast industrialization of developing countries, with a few exceptions. 
> raw materials factory are faster to make, to balance the demand increase and simulate early period industrialization start with low cost goods.
> computer related factory are faster to make to simulate the internet boom.

### CODE REVIEW

**Comment by settintotrieste** [comment]
I cannot accept this change.

1. The values must remain at 1 because of many modifiers that increase factory cost. I have attempted to increase costs before only to realise that in certain communist countries, the cost of a factory becomes astronomical.

2. It is necessary for factories to be built quickly to keep up with pop growth. Especially since each level only increases the workforce by 10,000. It is better to balance the growth of craftsmen population since it is the number of employed craftsmen alone that determines industry score.

**Comment by TK3600** [comment]
It seems alright in China. What are the examples of communist country that suffer from it? I will look into it in my playtest.

**Comment by settintotrieste** [comment]
IIRC it was Russia and North Korea.

**Comment by TK3600** [comment]
Alright, I will keep the files on my end until I am confident that Russian and North Korea will work. We can discuss then.

**Comment by settintotrieste** [comment]
Thanks

**Pull request closed without merging**
