### PR TITLE
Plus ultra loc fixes

### PR DESCRIPTION
**Pull request by ccfox**
Small loc changes that github is losing its mind over, as mentioned in #972.

### CODE REVIEW

**Comment by Outta-my-way-burrocrat** [comment]
This PR is reverting #965 somehow

**Comment by ccfox** [comment]
I have to complete more sacrifices for the github gods.

**Comment by Outta-my-way-burrocrat** [comment]
Github's built around the command line mostly, you're going to encounter problems with conflict resolution if you rely on the GUI.

**Comment by ccfox** [comment]
I do it all in browser, since installing the associated program would be bloatware - given that this is the only project I contribute to.

**Comment by ccfox** [comment]
That seems to have made things worse, github apparently just hates latin. I'm going to close this request and just make a new branch.

**Pull request closed without merging**
