### PR TITLE
Less starving aristocrats, more capitalists

### PR DESCRIPTION
**Pull request by Outta-my-way-burrocrat**
Mitigates the starving Executives problem by switching the Investor and Executive pops in history/pops. This merge conflicts with Elia's PR #962 but I can fix it if their PR is merged first.

### CODE REVIEW

**Comment by settintotrieste** [comment]
issue #969

**Comment by ccfox** [comment]
Switching out all those pops wouldn't have a negative impact on the changes to aristocrats themselves, I assume? The fact that for communist nations, they are the 'investors'?

**Comment by settintotrieste** [comment]
There should be no issue as an event will auto fire for any communist nation to demote all capitalists.

**Comment by settintotrieste** [comment]
Okay, I've edited the auto demote event for communists to convert capitalists to executives so any change here would not lead to issues as any executives converted to capitalists will re-convert back to executives. This change should also help to preserve the investment pool from being wiped out after a communist revolution as the money will remain available for factory construction through executives.

**Pull request merged**
