### PR TITLE
Update navy_tech.txt

### PR DESCRIPTION
**Pull request by TK3600**
Renamed anti ship ballistic missiles to modern anti ship missiles, because we already have another tech called "anti ship ballistic missile" without the s.

### CODE REVIEW

**Comment by settintotrieste** [comment]
There is a massive chunk of added techs in your pull request, was that intended?

**Comment by TK3600** [comment]
No????

**Comment by TK3600** [comment]
I am stupid, I will fix it right now.

**Comment by TK3600** [comment]
Done. Fixing bug only to create more bug, such is life.

**Pull request merged**
