### PR TITLE
Code cleanup by  Outta-my-way-burrocrat 

### PR DESCRIPTION
**Pull request by settintotrieste**
**Changed the internal names of many reforms and made tweaks**
- Trade union reforms no longer affect Intermarriage.
- Fixed and tweaked English, French, Occitan, Taiwanese union reforms and conscription reforms. A full review of all nation's trade union reforms is needed.
- Many events still use the civil_service reforms instead of public_meetings (assimilation_troubles, islamist_movements, political_events, political_liberal_revolutions, political_socialism_fascism).

### CODE REVIEW

**Comment by settintotrieste** [comment]
Hi @Outta-my-way-burrocrat, I wish to merge this branch with the master but just to double confirm, will there be more planned commits for this branch?

**Comment by Outta-my-way-burrocrat** [comment]
@settintotrieste One more commit then this is done

Should I update the events mentioned?

**Comment by Outta-my-way-burrocrat** [comment]
This block is done. I'll update conscription in another PR

**Comment by settintotrieste** [comment]
Alright, thanks!

**Pull request merged**
