### PR TITLE
Sphere bug fix (the forbidden update)

### PR DESCRIPTION
**Pull request by TK3600**
For reference only, just leave it here. If anyone want a taste of this game having sphere bug fixed, try this simple change.

Settin, you know you want to try deep inside!

### CODE REVIEW

**Comment by settintotrieste** [comment]
It's interesting but it is better if you don't use Nauru for this submod because they have events and decisions for them

**Comment by TK3600** [comment]
What do you think about Jan Mayen? In game it has 32k population, but irl it has no permanent residence, the army stationed at most was 32. You may want to look into that.

**Comment by settintotrieste** [comment]
If you can create a province for Jan Mayen then maybe I can put this in as an optional extra like performance mode.

**Comment by TK3600** [comment]
That is a brilliant idea, best of both world. I will get started on the work on it.

**Pull request closed without merging**
