### PR TITLE
UNSQ duplicate event fix and limits

### PR DESCRIPTION
**Pull request by ARR8**
Limits referring to only countries at peace getting the UNSG event and only UN members of vassals of such getting the global consciousness. Also tweaked the prestige values a little and minor cleanup.

Tested this - it does select all three kinds of secetaries-general and there is only one major event per selection.

### CODE REVIEW

**Comment by settintotrieste** [comment]
I believe the previous setup is better as it allows the player to know what type of Secretary General was selected straightaway from the event headline. So I will have to reject this PR unfortunately.

**Comment by ARR8** [comment]
Would it be better to add the word (Passive, Normal, Aggressive) into the title, or have it be its own line in the description?

**Comment by ARR8** [comment]
I've just now added the type of UNSQ to its own line in the description

**Comment by settintotrieste** [comment]
Great!

**Pull request merged**
