### PR TITLE
Cold War Enhancement Mod 1.16

### PR DESCRIPTION
**Pull request by Outta-my-way-burrocrat**
Not the best end for my contributions, but the mod is better at least. I'll stop Sept 28.

### CODE REVIEW

**Comment by Outta-my-way-burrocrat** [comment]
Fix candidates for the week:

Northern Afghanistan mechanics
Computers invention tweak
Western Sahara fix
Ship oobs

**Comment by settintotrieste** [comment]
Massive thanks for all your help over the years, wish you well! 🙂

**Comment by Outta-my-way-burrocrat** [comment]
Some of the last changes are experimental and thus not part of this push:
Doctor's strike bugfix: https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/pull/1172
HPM's dynamic RGO switching, fertilizer and merging rubber and plastic: https://github.com/settintotrieste/Victoria-2-Cold-War-Enhancement-Mod-CWE/pull/1162

**Comment by Outta-my-way-burrocrat** [comment]
No Afghan update :(

**Comment by Outta-my-way-burrocrat** [comment]
That is officially it.

**Comment by settintotrieste** [comment]
> No Afghan update :(
> That is officially it.

No worries, you’ve already done plenty. Thank you very much for all the amazing contributions over the years, wishing you all the best!

**Pull request merged**
