### PR TITLE
Paraguyans are platinean_white_spanish

### PR DESCRIPTION
**Pull request by Santiago2710**
Paraguyans are platinean_white_spanish, they are not andean_white_spanish, they are culturaly more closer to Uruguay and Argentina than Bolivia, Chile and Peru.

### CODE REVIEW

**Comment by ccfox** [comment]
Development has stopped on the main fork, but I'm more than happy to make this change on my fork of the mod. I also plan on adding Guarani, though that might take some time given that there are multiple groups and very poor demographic data from near the start date of the mod.

**Comment by Outta-my-way-burrocrat** [comment]
You might want to change Uruguay's pops as well.

**Comment by Santiago2710** [comment]
soryy i make i mistake, i am going to make a new PR that make the changes in paraguay pops.

on the other side, which thing i have to change in uruguay?, they are platinean_white_spanish already

**Comment by Outta-my-way-burrocrat** [comment]
Ah, I am also mistaken.

**Pull request closed without merging**
