### PR TITLE
Update army_tech.txt (addressing china soviet union mil score disparity)

### PR DESCRIPTION
**Pull request by TK3600**
Adjusted supply consumption with consideration of military score of developed nation vs developing nation. Tank tech now affect supply of affect unit type rather than all units.

### CODE REVIEW

**Comment by settintotrieste** [comment]
I think what should be done instead would be to remove all army_base supply costs increase for all techs other than those from the army and navy doctrine branch and use individual unit increases instead. Also supply_consumption should only be increased by 0.05 each time.

**Comment by TK3600** [comment]
The consumption should be OK, I lowered base cost of units, it should add up to status quo. I think the number is reasonable if you see how much larger vanilla vic 2 consumption increases.

If you lower the cost, we run into problem of india and china have too much mil score for low tech army.

If you lower base cost only, China will build more army now they have more money, manpower is never an issue for them.

**Comment by settintotrieste** [comment]
The problem is that the amount of supply consumed actually increases military score.

**Comment by TK3600** [comment]
Mil score is only an early game problem. Industry become the main source of score in mid and late game. By reducing base consumption, it will matigate the early game problem. The tech increase should not actually impact ranking, if not helping developed country have better mil score than lesser ones.

**Comment by TK3600** [comment]
I define early game as in 1976 and earlier. If you check out my latest report, the ranking is actually reasonable.

**Comment by settintotrieste** [comment]
From my test run with the current industry set up and no major wars but just before the -50% supply cost reduction tweak, the PRC had 16K military score which made them rank 2 displacing the USSR in 1981. China had only 169 industry score and 2K prestige compared to Russia which had 3.6k industry score, 4K military score and 6K prestige. After applying the -50% supply reduction modifier to the savegame, China’s score shrank to 7.8K while Russia shrank to 3K. China was still no.2.

**Comment by TK3600** [comment]
How did China afford so much army?

**Comment by TK3600** [comment]
I honestly think it is a separate problem the fact someone can afford so much army....

And why is Russian prestige so low? Soviet collapsed?

**Comment by settintotrieste** [comment]
The AI will always build units to max out their cap until it goes bankrupt then they will disband all units. Even with 5% soldier pop, China will still have around 500-700 divisions and the supply consumption of that jacks it up to astronomical levels. Personally I don’t find having a large army a problem because due to the code, it is either a large army or a small one for all nations. I prefer the former because it helps the AI to finish off the historical wars without taking forever and gives players of smaller nations a chance to do something fun.

**Pull request closed without merging**
